### ISSUE TITLE
Hitch packaging

### ISSUE THREAD

**Issue by craigcarnell** [varnish/hitch#262] opened 2018-04-18 10:31 UTC
Hi,

Could Hitch 1.4.7 be updated in Ubuntu's packaging for 18.04 please? It's still 1.4.4

**Comment by craigcarnell** [comment] 2018-04-18 10:39
Or rather 1.4.8 as i've just seen in the other issue :+1:

**Comment by dugwood** [comment] 2018-04-19 12:07
And Debian please :-) It should be available as Varnish is on packagecloud: https://packagecloud.io/varnishcache/varnish60 as it's the same company behind it, isn't it?

Thanks!

**Comment by Dridi** [comment] 2019-01-11 11:01
Please get in touch with the Debian and Ubuntu package maintainers for Hitch and let them know that we don't break compatibility (on purpose) so to our knowledge this should be safe to upgrade even in a stable release.

I'm closing this one as a duplicate of #215.

**Closed** 2019-01-11 11:01 UTC
