### ISSUE TITLE
ECDH public server param reuse

### ISSUE THREAD

**Issue by phoenix-bjoern** [varnish/hitch#165] opened 2017-02-07 11:12 UTC
Similar to #134 SSL Labs has a new check for ECDH which fails on CentOS 7.3 and OpenSSL 1.0.1e (distributed with OS).
While the "DH param reuse" issue has been fixed in 1.4.4 it would be great to also fix the similar issue with ECDH.

**Comment by daghf** [comment] 2017-02-07 12:58
Hi Björn,

I believe this is a duplicate of https://github.com/varnish/hitch/issues/155

Fixed in 5839af05bfc76c2ff4b3cf40072ac637e89dc458

**Closed by daghf** 2017-02-07 12:58 UTC

**Comment by phoenix-bjoern** [comment] 2017-02-09 10:01
Fantastic, thanks @daghf !
