### ISSUE TITLE
Bug:  Configuration file requires spaces around configuration items

### ISSUE THREAD

**Issue by hookenz** [varnish/hitch#162] opened 2017-02-01 03:48 UTC
I spent ages trying to figure out why the pem-file was being ignored.

My hitch.conf contained:

`pem-file="/etc/hitch/example.pem"`

But when starting hitch, it complained:

> No x509 certificate PEM file specified

Changing the hitch.conf to:

`pem-file = "/etc/hitch/example.pem"`

And it now works.  I guess the parsing logic needs to be cleaned up a little.

**Comment by daghf** [comment] 2017-02-08 10:52
Hi @hookenz 

I can't reproduce this in the current release. Which version are you running?

**Comment by hookenz** [comment] 2017-02-10 01:10
@daghf  - 1.1.1.  

I should probably point out it may not be all config items.  That was an assumption.  Specifically it was configuration item named `pem-file`


> ubuntu@ip-10-0-0-48:~$ cat /etc/hitch/hitch.conf 

```
frontend = "[*]:443"
backend = "[127.0.0.1]:8080"
ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
workers = 2
pem-file="/etc/hitch/otoyhost.net.pem"
daemon = off
user = nobody
group = nogroup
```

> ubuntu@ip-10-0-0-48:~$ hitch --config=/etc/hitch/hitch.conf
> No x509 certificate PEM file specified!
> 

However, when I add spaces around the `pem-file` item.

> ubuntu@ip-10-0-0-48:~$ sudo hitch --config=/etc/hitch/hitch.conf
> 20170210T011014.219194 [20213] {core} hitch 1.1.1 starting
> 20170210T011014.219238 [20213] {core} Using OpenSSL version 1000207f.
> 20170210T011014.219352 [20213] {core} Listening on 0.0.0.0:443
> 20170210T011014.219382 [20213] {core} Listening on [::]:443
> 20170210T011014.219392 [20213] {core} Loading certificate pem files (1)
> 20170210T011014.221057 [20213] {core} Using DH parameters from /etc/hitch/otoyhost.net.pem
> 20170210T011014.221080 [20213] {core} DH initialized with 2048 bit key
> 20170210T011014.221184 [20213] {core} ECDH Initialized with NIST P-256
> 20170210T011014.221441 [20214] {core} Process 0 online
> 20170210T011014.221471 [20213] {core} hitch 1.1.1 initialization complete
> 20170210T011014.221512 [20214] {core} Successfully attached to CPU #0
> 20170210T011014.221573 [20215] {core} Process 1 online
> 20170210T011014.221667 [20215] {core} Successfully attached to CPU #1

**Comment by daghf** [comment] 2017-02-10 07:17
Hi - Thanks for getting back to us.

The configuration file parsing had quite a revamp for 1.2.0. Simply upgrading to a more recent should release should take care of it.

I'm closing this issue now.

**Closed by daghf** 2017-02-10 07:17 UTC
Labels: enhancement

**Comment by luckypoem** [comment] 2018-12-07 01:47
@hookenz 

root@wh:~# hitch --ssl --ciphers="EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" --backend=[localhost]:8118 --frontend=[0.0.0.0]:3399
No x509 certificate PEM file specified for frontend '[0.0.0.0]:3399'!
root@wh:~# 

what to add after the command:
hitch --ssl --ciphers="EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" --backend=[localhost]:8118 --frontend=[0.0.0.0]:3399 ?

and can u paste ur hitch.conf file here?
i want to view its format.

thank u a lot.

**Comment by luckypoem** [comment] 2018-12-07 01:50
@hookenz 
oh, i see ur hitch.conf file already.but 
what to add after the command:
hitch --ssl --ciphers="EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" --backend=[localhost]:8118 --frontend=[0.0.0.0]:3399 ?

thank u
