### ISSUE TITLE
Wrong default certificate with no SNI after certificate removal and hot-reload

### ISSUE THREAD

**Issue by bago** [varnish/hitch#276] opened 2018-07-26 10:41 UTC
I've upgraded from 1.4.4 to 1.4.8 in a "multihomed" setup (multiple IPs with their own certificates and multiple certificates for each IP). I had to skip 1.4.5, 1.4.6 and 1.4.7 because of issues handling the multihoming.

Now, I just noticed that when the client does not support SNI, hitch 1.4.4 was using the FIRST "pem-file" for that frontend in the handshake. Now with 1.4.8 it sounds like with no SNI it uses a "random" certificate.

Can you confirm the behaviour have been changed? Is it a bug or simply a change? Is there any workaround to force a specific certificate to be used when there is no SNI handshake?

**Comment by bago** [comment] 2018-07-26 11:17
I have to add that I extensively use hot-reloading when I automatically renew the certificates multiple times per day.

I tried restarting hitch (real restart) and the default certificate is CORRECTLY the first one declared... so I guess the "default" is broken during the hot reloading.

**Comment by bago** [comment] 2018-07-26 13:46
My case is the "default" used when the client does NOT support SNI. After the restart I can confirm that this is the FIRST one and not the last one (I've double checked with https://www.ssllabs.com/ssltest/ ).

I see there's a testcase for the case:
https://github.com/varnish/hitch/blob/master/src/tests/test05-multiple-listen-SNI.sh
But maybe it does not correctly emulate a client not-supporting SNI... and doesn't test reloading after new certificates are added or old dropped.

**Comment by Dridi** [comment] 2018-07-26 13:53
Do you have a minimal configuration you could share to reproduce the behavior you are observing? Only the hitch configuration with dummy host names, I'll attempt a test case with the dummy certificates we use.

**Comment by bago** [comment] 2018-07-26 14:38
The fact is that I'm not able to easily reproduce it..

I find the server with wrong default certificates... I restart it and everything come back to normal (first certificate in the declaration is sent as default).

I attempted adding a new certificate and doing an hot reload and everything is still ok... 

BTW the frontend confs are simple:

```
frontend = {
  host = "IP.ADDRESS.1"
  port = "443"
  pem-file = "/etc/hitch/certs/defaultwildcard.pem"
  pem-file = "/etc/hitch/certs/acmemanagedhost.pem"
  pem-file = "/etc/hitch/certs/acmemanagedthirdhost.pem"
}
```

I have 4 frontends on 4 different IPs and the largest frontend uses 400 pem-files declarations.
The acme pems are added, removed, renewed often and I have multiple hitch hot reloads per day.
This "first" (default) certificate is never removed or added, but it is renewed.

PS: doing some check I found that openssl client up to 1.1.0 does not use SNI if you don't use -servername directive, but with openssl 1.1.1  you have to use -noservername directive, otherwise it will pass servername depending on the host used to connect.

**Comment by Dridi** [comment] 2018-07-26 15:06
> maybe pem-files in command line are handled in a different order than pem-files in the cfg ?

That's why I was asking for your configuration. I'd like to hunt inconsistencies but first in need a lead :)

> PS: doing some check I found that openssl client up to 1.1.0 does not use SNI if you don't use -servername directive, but with openssl 1.1.1 you have to use -noservername directive, otherwise it will pass servername depending on the host used to connect.

Oh great Someone:tm: will have to teach the test suite how to handle those differences. Thanks a lot!

> Given a simple "pem-file" addition did not let me reproduce the issue I can only guess, either:
A) it only happens randomly (racing issue)
B) it only happens when you remove a certificate (can't test right now)
C) it only happens when you renew the default certificate (maybe hitch remove the old one and adds the new one at the end instead of "replacing it").

I really like the C option because it's a scenario that makes sense. A is scary, and unlikely during the setup phase, and given our data structures B is rather unlikely too. And given the "randomness" of a user's operations (eg if you have automation in place for reloads and can't predict their order) then we move the alleged race from A outside of Hitch.

**Comment by bago** [comment] 2018-07-27 08:14
Here I am...

I reduced the case to "**B) it only happens when you remove a certificate**".

So I remove one of the certificates from the conf (not the default one, but one in the middle of the list) and then issued a "kill -HUP" and now another random host is the new default (the removed one was the 10th in the list, the new default is around the 60 position over 400, so it is not the previouis/next of the removed one).

So I guess to reproduce it you have to

start with
```
frontend = {
  host = "IP.ADDRESS.1"
  port = "443"
  pem-file = "/etc/hitch/certs/defaultwildcard.pem"
  pem-file = "/etc/hitch/certs/acmemanagedhost.pem"
  pem-file = "/etc/hitch/certs/acmemanagedthirdhost.pem"
}
```

change the file to
```
frontend = {
  host = "IP.ADDRESS.1"
  port = "443"
  pem-file = "/etc/hitch/certs/defaultwildcard.pem"
  pem-file = "/etc/hitch/certs/acmemanagedthirdhost.pem"
}
```

and "kill -HUP" and check the new default.

If it doesn't reproduce then the options are
1) Do an "add new pem-file" between the 2 steps (I have to do this in my live setup)
2) Make an large list of pem-files (if the behaviour is "random" then a random of 2 may give you 50% of false positives). Btw if this is the case you could see the test failing randomly.

**Comment by bago** [comment] 2018-07-27 08:41
I guess the issue must be in cert_query https://github.com/varnish/hitch/blob/master/src/hitch.c#L3536 but I don't know hitch internals enough to identify it.

I see init_certs have calls to insert_sni_names while cert_query do them in cert_commit and cert_commit is called for removed certificates BEFORE the default certificates.. just trying to guess as I really don't know the code.

**Comment by Dridi** [comment] 2018-07-27 13:19
I added a `stop_hitch` fixture for the test suite, in order to stop and start a new instance in the same test case. If I add a conffig-file variant to the test case 5 I can reproduce the fallback-last vs fallback-first inconsistency:

```diff
diff --git i/src/tests/test05-multiple-listen-SNI.sh w/src/tests/test05-multiple-listen-SNI.sh
index 89bc4ea..60d3d75 100755
--- i/src/tests/test05-multiple-listen-SNI.sh
+++ w/src/tests/test05-multiple-listen-SNI.sh
@@ -19,3 +19,26 @@ s_client -servername site1.example.com >sni.dump
 run_cmd grep -q 'subject=/CN=site1.example.com' sni.dump
 
 curl_hitch
+
+stop_hitch
+
+cat >hitch.cfg <<EOF
+frontend = {
+       host = "localhost"
+       port = "$LISTENPORT"
+
+       pem-file = "${CERTSDIR}/site1.example.com"
+       pem-file = "${CERTSDIR}/site2.example.com"
+       pem-file = "${CERTSDIR}/default.example.com"
+}
+
+backend = "[hitch-tls.org]:80"
+EOF
+
+start_hitch --config=hitch.cfg
+
+s_client >cfg-no-sni.dump
+run_cmd grep -q 'subject=/CN=default.example.com' cfg-no-sni.dump # FAILURE HERE
+
+s_client -servername site1.example.com >cfg-sni.dump
+run_cmd grep -q 'subject=/CN=site1.example.com' cfg-sni.dump
```

Next, Someone:tm: should write a reproducer for the reload-after-remove inconsistency.

**Comment by Dridi** [comment] 2018-07-27 14:32
https://github.com/varnish/hitch/blob/feaa455db8c2ae57249096d0abdd7f65398a73ac/docs/installation.md#L19-L21

See https://github.com/varnish/hitch/blob/master/docs/installation.md#installing-from-source

To run the test suite: `make check VERBOSE=1`.

**Comment by bago** [comment] 2018-07-27 15:06
Well, for sure it's clear I didn't dig too much in the docs ;-) Thank you! I hope I will be able to give you something back!

**Comment by Dridi** [comment] 2018-07-27 15:13
You already did, don't worry about that. I don't have much time to spend on this, but I wanted to have some test cases ready for the team before our weekly bug wash next Monday.

**Comment by bago** [comment] 2018-07-27 15:57
Succesfully built it, I guess I also got a test proving the bug... I'll PR soon.

**Comment by Dridi** [comment] 2018-07-27 16:46
I had a quick look earlier and nailed it to the hash table of pem certificates used by frontend.

Fall back to first:

```
frontend = {
       host = "localhost"
       port = "$LISTENPORT"

       pem-file = "${CERTSDIR}/site1.example.com"
       pem-file = "${CERTSDIR}/site2.example.com"
       pem-file = "${CERTSDIR}/default.example.com"
}
```

Fall back to last:

```
pem-file = "${CERTSDIR}/site1.example.com"
pem-file = "${CERTSDIR}/site2.example.com"
pem-file = "${CERTSDIR}/default.example.com"

frontend = {
       host = "localhost"
       port = "$LISTENPORT"
}
```

**Comment by bago** [comment] 2018-07-27 16:50
Well, I tried to reproduce it but I failed:
https://github.com/bago/hitch/blob/master/src/tests/test29-reload-after-cert-removal-check-default-SNI.sh

My live deployment uses the prebuilt binaries from el7 rpm.
I tried extracting the hitch.tar.gz from the src.rpm and build/test it but can't reproduce it there neither...

For the record this is my reduced live conf... maybe looking at it you can identify something weird that I should investigate in the testing:



```
backend = "[127.0.0.1]:6081"
pem-file = ""
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2
ciphers = "-MEDIUM:-LOW:-aNULL:-eNULL:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:AES128-GCM-SHA256:AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES256-GCM-SHA256:AES256-SHA:DES-CBC3-SHA"
prefer-server-ciphers = on
ssl-engine = ""
workers = 1
backlog = 100
keepalive = 3600
chroot = ""
user = "hitch"
group = "hitch"
quiet = on
syslog = on
syslog-facility = "daemon"
daemon = off
write-ip = off
write-proxy-v1 = off
write-proxy-v2 = on
proxy-proxy = off
sni-nomatch-abort = off
frontend = {
  host = "XXX.XXX.XXX.173"
  port = "443"
  pem-file = "/etc/hitch/certs/_.wildcardA.it.pem"
  pem-file = "/home/sharedmnt/acme/live/host.domain1.it/haproxy"
  # 15 pems ....
  pem-file = "/home/sharedmnt/acme/live/host.domain420.it/haproxy"
}
frontend = {
  host = "XXX.XXX.XXX.174"
  port = "443"
  pem-file = "/home/sharedmnt/acme/live/default.domainB.it/haproxy"
  pem-file = "/etc/hitch/certs/_.wildcardB.it.pem"
  pem-file = "/home/sharedmnt/acme/live/default.domainB.it/haproxy"
}
frontend = {
  host = "XXX.XXX.XXX.175"
  port = "443"
  pem-file = "/etc/hitch/certs/_.wildcardC.it.pem"
  pem-file = "/home/sharedmnt/acme/live/host.domain1000.it/haproxy"
  # 400 pems ....
  pem-file = "/home/sharedmnt/acme/live/host.domain1420.it/haproxy"
}
frontend = {
  host = "XXX.XXX.XXX.176"
  port = "443"
  pem-file = "/etc/hitch/certs/_.wildcardD1.it.pem"
  pem-file = "/etc/hitch/certs/_.wildcardD2.it.pem"
  pem-file = "/etc/hitch/certs/_.wildcardD3.it.pem"
  pem-file = "/etc/hitch/certs/_.wildcardD4.it.pem"
  pem-file = "/etc/hitch/certs/_.wildcardD5.it.pem"
}
```

**Comment by bago** [comment] 2018-08-01 16:58
Another round, again broken...
30/07 18:20: restart: default ok
31/07 06:20: reload with 4 certificates renewed: default is ok
01/08 06:20: reload with 1 certificate renewed: default is ok
01/08 15:50: reload with 2 NEW certificates: default broken
01/08 16:30: restart: default ok

**Comment by bago** [comment] 2018-08-03 15:52
Happened again, this time NO changes to the conf file at all, only 4 existing certificates renewed (yesterday 3 certificates renewed and the reload worked fine, so it doesn't happen "always").

Running multiple "kill -HUP" when there are no changes to the conf or the certificates doesn't break nor fix it.

**Comment by daghf** [comment] 2018-08-23 07:38
Hi @bago

Thanks a lot for your help in diagnosing this. I've now pushed a fix in ee2b44b8a8b1b27b2b36acc86f18c0666e658e6f. Would you mind giving latest master a try?

**Comment by bago** [comment] 2018-08-23 08:03
Great! Unfortunately the tests I wrote were unable to prove the bug, so pulling the latest code won't show changes and I can only use "official" rpms in the live environment showing the issue.

I'll try this in my dev setup but I hardly reproduced the bug here....

I checked the fix but I don't know the code enough to understand what was the "exact issue": maybe if I understand it I can write a test-case to prove the bug in a reproducible way and we can see it doesn't fail in the latest code.

**Comment by Dridi** [comment] 2018-08-23 10:15
@bago please also note that your fallback certificate will now be the _last_ certificate as per the documentation. I'm reopening this to give you an opportunity to report back to us and to make sure we make this fix very visible in the next release notes!

**Comment by bago** [comment] 2018-09-14 08:42
I just built a dev rpm from the latest sources and deployed it since an hour. I can confirm that now the default is the last one and not the first one. I'll update in the next days about the "reloads" effects.

**Comment by bago** [comment] 2018-09-17 11:26
After 3 days and a few reloads/renews/add/removal hitch-dev keeps offering the correct default certificate.

**Closed** 2018-09-17 11:27 UTC
