### ISSUE TITLE
using 443 as a frontend port

### ISSUE THREAD

**Issue by shauligal** [varnish/hitch#168] opened 2017-02-21 20:39 UTC
I'd like to terminate TLS that comes to port 443:
hitch --ssl --backend=[127.0.0.1]:8000 --frontend=[*]:443 shauli.pem

The problem is that hitch needs the root permissions in order to bind a system port ("{bind-socket}: Permission denied: [*]:443").

When I try to run it as root, I'm getting the following error:
"{core} ERROR: Refusing to run workers as root."

Any idea?

**Comment by Dridi** [comment] 2017-02-21 20:57
This is not specific, any process needs privileges to bind low ports.

Try running it as root (for example `sudo hitch ...`) but this is not a support channel. Please only open issues on github for actual bugs.

**Comment by Dridi** [comment] 2017-02-21 20:58
OK, I missed the bit on "Refusing to run workers as root."

Reopening.

**Comment by Dridi** [comment] 2017-02-21 21:01
See the `hitch(1)` manual for setting the user/group from the command line (`-u` and `-g`) which can also be defined in the configuration file.

Closing again on the ground that this is not a bug.

**Closed by Dridi** 2017-02-21 21:01 UTC
Labels: invalid
